default: &default
  adapter: postgresql
  username: postgres
  encoding: unicode
  host: db
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yummy_api_development

test:
  <<: *default
  database: yummy_api_test

production:
  <<: *default
  database: yummy_api_production
  username: yummy_api
  password: <%= ENV["YUMMY_API_DATABASE_PASSWORD"] %>
